# Generated by Django 4.2.11 on 2024-03-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydetails', '0003_alter_countrydetail_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydetail',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=200),
            preserve_default=False,
        ),
    ]
